import type { Metadata } from "next";
import "./reset.css";
import "./globals.css";
import Header from "@/components/modules/Header/Header";
import Footer from "@/components/modules/Footer/Footer";
import ProviderComponent from "@/components/Provider/Provider";
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store";
import AppBar from "@/components/AppBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProviderComponent>
            <html lang="en">
                <body>
                    <AppBar />
                    <Header />
                    {children}
                    <Footer />
                </body>
            </html>
        </ProviderComponent>
    );
}
